### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by tekool** [PureMVC/puremvc-js-util-pipes#1]
The project misses Unit Tests that however exist in AS3 version : https://github.com/PureMVC/puremvc-as3-util-pipes-unittests/wiki

**Comment by cliffhall** [comment]
Yep, haven't linked it into the big wiki yet for that reason. I was working on docs yesterday. don't yet know about units.

**Comment by cliffhall** [comment]
I just changed the wiki to say Status: In Development

**Comment by tekool** [comment]
Now I realize I should have reported the issue in the billdwhite Github project. I've duplicated the issue in its Github. You may close the issue here in PureMVC as you want.

Opened issue : https://github.com/billdwhite/puremvc-js-pipes/issues/1

**Comment by cliffhall** [comment]
Well, it will need to be fixed here. This is not a fork of his project. His
project is not setup the way we will do it here. It includes the demo, and
links to all the other projects for UI components, dojo, etc, which don't
need to be in the pipes project. I created this project, extracted his pipes
code and fixed the documentation. I plan to extract the demo from his
project and make another repo with it.

-=Cliff>

**Comment by tekool** [comment]
Ah? It's so sad to loose fork and work history on the project, it helps a lot in understanding how the contributors made the project and how it evolved at first. And it's a great motivation for them to optionnaly have their career promoted by a fork from a project of theirs on PureMVC. This is the best way to increase PureMVC popularity and contributors.

There's a lot to say about this, in fact. PureMVC Github is actually not made like other projects on Github. The standard way of handling things on Github (and in fact git) would have been to make a repository for each language and  include a demo directory in it ( like TodoMVC does https://github.com/addyosmani/todomvc ). It's natural with git to fork, add a directory in the contributor local repository and finally make a pull request on the existing project. This is really beautiful, because Github would handle all the work for commenting on defects, blame line of codes, ask for changes back and forth before really including the demo in the project. This would have the great advantage to let any PureMVC team member to help you on this work also. The great advantage of this is also that each demo directly link a specific version of PureMVC and it can be updated easily without any pain as users would have to integrate their demo in the language repository build. But we both know the huge work it would be to make this changes on the existing repositories.

So, having a repository for each demo/util/unit-test is not mandatory, but at least I think we must keep track of the original repo. You always can delete unwanted things, update readmes etc. and after all that, send a pull request to the contributor via the Github interface to make him integrate changes (he can continue his work in a branch) and update it back. This is how things work on Github from what I know and this work pretty good because all is managed via Github, no more e-mail, no more long wait before a project to be integrated etc. updates can be asked only using an issue report like here.

**Comment by cliffhall** [comment]
I agree that if the repo that I'm pulling from is close to being in the
shape we want that forking is the way to go. However, the name of the repo
and its contents are important to me. I have nearly 100 projects, and it is
important for them to be normalized as much as possible. I don't mind
including unit tests in a project, but demos are separate. This repo has
three versions of pipes, a demo, and all these other projects, which are not
needed with the base pipes utility. 

I could ask Bill to break all this out himself and make a pipes repo that
matches what the other pipes ports contain, but he's already done quite a
bit of work and I had the time to do this. 

As to the loss of history, I agree that on a large, evolving project, that
is really important. But this is a port of a utility. Once it is stable,
that's pretty much it. Of course it could be improved, but I would suggest
he fork the official repo, modify and send a pull request. 

I think this decision has to happen on a case by case basis. For instance,
you mentioned you'd rename your TypeScript port's repo so that it matches
the naming conventions in play with the other PureMVC repos. And having
worked on so many of these projects, I'm sure your project's contents will
be basically what is expected and no more. In that case, I'll fork your repo
to PureMVC certainly. 

-=Cliff>

**Comment by tekool** [comment]
> I could ask Bill to break all this out himself and make a pipes repo that
> matches what the other pipes ports contain

In fact, if you fork his project, you can delete and modify everything you want and so make yourself the pull request clicking on a button. He wouldn't have any additional work to do except clicking on a button too. This is why forking is beautiful. ;)

**Comment by cliffhall** [comment]
I couldn't rename his repo, or split the demo to another repo he owns that way, though.

-=Cliff>

**Comment by tekool** [comment]
You could. I've just tested and you can do that (using the web interface, I don't have the Github application). 

1) Fork a project from anyone (no options there to give a new name to your repository which I agree is shit ).
2) Go into the admin tab of the created repository 
3) Rename the fork. It will continue to let the fork appear and any functionnality handled by Github whatever the message displayed says.

**Comment by cliffhall** [comment]
Ok, that's good to know. In the future I'll certainly consider forking and renaming. But the changes to this repo also entail splitting the repo into another for the demo. Again I could ask Bill to do that first, but I had some time available, so I went ahead and made this repo and copied in the needed code, which now has modifications. So for this project I will make the two official repos this way. I'll start with some of your repos forking to PureMVC and see how that goes.

-=Cliff>

**Comment by tekool** [comment]
Of course, you know I'm the first to understand that our time is quite limited, I'm currently having hard time with the PureMVC Employee Admin demo for TypeScript. I just want to share my thoughts on how this may work, I don't want to give you additional extra uneeded work.

**Comment by cliffhall** [comment]
No worries. I do appreciate the input, and I am fairly in agreement with you about how this should usually work going forward. Preserving the history of a project is a good thing and should be done where possible. In this case, I would be removing a lot of stuff, and I'm sure Bill wouldn't want to pull those changes back to his repo, ditching his dojo stuff, etc. If it were only a minor rearrangement that he would then pull back and line his project up with this one then forking would be the right way.

**Comment by billdwhite** [comment]
Just to chime in here:  I appreciate tekool's points on this, but I'm perfectly fine with cliff doing whatever he needs to do to get the code in place.  I'm still getting familiarized with github's workflow so I'm not too particular about how things get handled with respect to forking, etc.  I'm just glad that I could contribute back to a codebase that has been of such great value to my projects over these past several years.

**Comment by tekool** [comment]
Yes, I think we're all agree that Cliff make a huge work on PureMVC all days and specifically moving sources from SVN to Github. I'm thankful for that, I really don't want PureMVC to lose its popularity and this will help a lot to be on Github. 

Bill, while we're on that, I also realize that your solution of using Git submodules could be the right choice for the problem I told on demos not being directly linked to a specific PureMVC version. This could be a good convention to create every new util or demo using a submodule for the PureMVC library from the corresponding PureMVC Github. Having easy to update PureMVC library version and sources could help a lot in maintenance.

**Comment by cliffhall** [comment]
Thanks Frederic, for your discussions that got me to actually do it. It was
a long row to hoe, but finally we're here and it's sooooo much better. And I
am keen to make sure to look at how things are done here and incorporate
what makes sense. 

When I looked at Bill's project and saw the submodules, I was thinking about
that as well. 

Currently, each util or demo has its own copy of the compiled or minified
PureMVC library it depends upon. If a demo were to use Github submodules
instead, the resultant project download would include the source of the
other project as a sibling to source of the demo. That would make the
project, in most cases, have a layout that isn't the usual layout. By usual
layout, I mean "libraries live in a lib folder containing all the compiled
or minified libraries being used". The user is forced to download a bunch of
files they probably don't need to see. I'm somewhat concerned that this
would reduce the effectiveness of the demo or util from that perspective. 

This looks like SVN externals to me. I'll look into it, but if we can point
to a single file in a repository (instead of having to include the entire
repository), and we can do that at whatever level we want (i.e., doesn't
have to be at our repo's root, but could be in a folder like lib), then
maybe this would work.

However we'd have to point to the file on a specific tag, keep old versions
available, or remove the version number from the compiled or minified lib.
None of that sounds like a win over just including the current lib you're
building on. 

Also, if there are libraries that don't exist as GitHub libraries, you'd
have to include them the old fashioned way (lib folder) anyway. So your out
of box project setup might be more complex because it has to include libs
from different folders instead of just one.

**Comment by cliffhall** [comment]
Thanks Bill. What I'm thinking is you can fork the project I've made, do any
changes like unit tests if you're up to it (I'll take a crack at them if
you'd rather not). Any changes on your fork, then you send a pull request
and I merge the changes. There's also a way, I believe, for you to receive
upstream changes from my repo, but I'm not that advanced yet either. Still
mostly using the GitHub app. 

-=Cliff>

**Comment by tekool** [comment]
@cliffhall Ah! I agree with you, having to pull the whole repository from the other Github is too much. However, this can be located in the lib folder. And yes this works as SVN externals.

I will ask to colleagues of mine here at work, we've switched to git recently and start to have some knowledge in there. I'll can't answer this before monday this said.

**Comment by tekool** [comment]
Googling a little for this submodules story I found this on stackoverflow http://stackoverflow.com/questions/5303496/how-to-change-a-git-submodule-to-point-to-a-subfolder

It clearly says we cannot have only part of a repo into another one.

This is too bad because it would have been a good idea for you to directly use the README file located into the master as home for the wiki page using this.

This said there is some good idea to have from this like : if you plan to manage a wiki for PureMVC on Github using gh-pages. They said that submodules automatically updates their sources each time you edit a page ( https://help.github.com/articles/using-submodules-with-pages ), this would be a good entry point to expose each README file for each repo from PureMVC that would always be updated without any pain.
